package(default_visibility = ["//visibility:public"])

cc_library(
    name = "fastfhir_runtime",
    deps = [
        "@fastfhir//:fastfhir",
        "@fastfhir//:fastfhir_ingestor",
    ],
)

cc_library(
    name = "google_fhir_runtime",
    deps = [
        "//third_party/google_fhir:r4_core_protos",
    ],
)
