// ============================================================
// This file is autogenerated by FastFHIR. DO NOT EDIT.
// Copyright (c) Ryan Landvater. All rights reserved.
// ============================================================
#pragma once
#include "FF_DataTypes.hpp"

struct BundleData;
struct BundleentryData;
struct BundleentryrequestData;
struct BundleentryresponseData;
struct BundleentrysearchData;
struct BundlelinkData;

struct BundlelinkData {
    std::string_view id;
    std::vector<ExtensionData> extension;
    std::vector<ExtensionData> modifierextension;
    std::string_view relation;
    std::string_view url;
};

Size SIZE_FF_BUNDLE_LINK(const BundlelinkData& data, uint32_t __version = FHIR_VERSION_R5);
Offset STORE_FF_BUNDLE_LINK(BYTE* const __base, Offset start_off, const BundlelinkData& data, uint32_t __version = FHIR_VERSION_R5);
BundlelinkData FF_DESERIALIZE_BUNDLE_LINK(const BYTE* const __base, Offset __offset, Size __size, uint32_t __version);

struct BundleentryrequestData {
    std::string_view id;
    std::vector<ExtensionData> extension;
    std::vector<ExtensionData> modifierextension;
    HTTPVerb method = HTTPVerb::Unknown;
    std::string_view url;
    std::string_view ifnonematch;
    std::string_view ifmodifiedsince;
    std::string_view ifmatch;
    std::string_view ifnoneexist;
};

Size SIZE_FF_BUNDLE_ENTRY_REQUEST(const BundleentryrequestData& data, uint32_t __version = FHIR_VERSION_R5);
Offset STORE_FF_BUNDLE_ENTRY_REQUEST(BYTE* const __base, Offset start_off, const BundleentryrequestData& data, uint32_t __version = FHIR_VERSION_R5);
BundleentryrequestData FF_DESERIALIZE_BUNDLE_ENTRY_REQUEST(const BYTE* const __base, Offset __offset, Size __size, uint32_t __version);

struct BundleentrysearchData {
    std::string_view id;
    std::vector<ExtensionData> extension;
    std::vector<ExtensionData> modifierextension;
    SearchEntryMode mode = SearchEntryMode::Unknown;
    double score = FF_NULL_F64;
};

Size SIZE_FF_BUNDLE_ENTRY_SEARCH(const BundleentrysearchData& data, uint32_t __version = FHIR_VERSION_R5);
Offset STORE_FF_BUNDLE_ENTRY_SEARCH(BYTE* const __base, Offset start_off, const BundleentrysearchData& data, uint32_t __version = FHIR_VERSION_R5);
BundleentrysearchData FF_DESERIALIZE_BUNDLE_ENTRY_SEARCH(const BYTE* const __base, Offset __offset, Size __size, uint32_t __version);

struct BundleentryresponseData {
    std::string_view id;
    std::vector<ExtensionData> extension;
    std::vector<ExtensionData> modifierextension;
    std::string_view status;
    std::string_view location;
    std::string_view etag;
    std::string_view lastmodified;
    ResourceReference outcome = {};
};

Size SIZE_FF_BUNDLE_ENTRY_RESPONSE(const BundleentryresponseData& data, uint32_t __version = FHIR_VERSION_R5);
Offset STORE_FF_BUNDLE_ENTRY_RESPONSE(BYTE* const __base, Offset start_off, const BundleentryresponseData& data, uint32_t __version = FHIR_VERSION_R5);
BundleentryresponseData FF_DESERIALIZE_BUNDLE_ENTRY_RESPONSE(const BYTE* const __base, Offset __offset, Size __size, uint32_t __version);

struct BundleentryData {
    std::string_view id;
    std::vector<ExtensionData> extension;
    std::vector<ExtensionData> modifierextension;
    std::vector<BundlelinkData> link;
    std::string_view fullurl;
    ResourceReference resource = {};
    std::unique_ptr<BundleentrysearchData> search;
    std::unique_ptr<BundleentryrequestData> request;
    std::unique_ptr<BundleentryresponseData> response;
};

Size SIZE_FF_BUNDLE_ENTRY(const BundleentryData& data, uint32_t __version = FHIR_VERSION_R5);
Offset STORE_FF_BUNDLE_ENTRY(BYTE* const __base, Offset start_off, const BundleentryData& data, uint32_t __version = FHIR_VERSION_R5);
BundleentryData FF_DESERIALIZE_BUNDLE_ENTRY(const BYTE* const __base, Offset __offset, Size __size, uint32_t __version);

struct BundleData {
    std::string_view id;
    std::unique_ptr<MetaData> meta;
    std::string_view implicitrules;
    std::string_view language = "";
    std::unique_ptr<IdentifierData> identifier;
    BundleType type = BundleType::Unknown;
    std::string_view timestamp;
    uint32_t total = FF_NULL_UINT32;
    std::vector<BundlelinkData> link;
    std::vector<BundleentryData> entry;
    std::unique_ptr<SignatureData> signature;
    ResourceReference issues = {};
};

Size SIZE_FF_BUNDLE(const BundleData& data, uint32_t __version = FHIR_VERSION_R5);
Offset STORE_FF_BUNDLE(BYTE* const __base, Offset start_off, const BundleData& data, uint32_t __version = FHIR_VERSION_R5);
BundleData FF_DESERIALIZE_BUNDLE(const BYTE* const __base, Offset __offset, Size __size, uint32_t __version);

namespace FastFHIR {
template<> struct TypeTraits<BundlelinkData> {
    static constexpr auto recovery = RECOVER_FF_BUNDLE_LINK;
    static Size size(const BundlelinkData& d, uint32_t v = FHIR_VERSION_R5) { return SIZE_FF_BUNDLE_LINK(d, v); }
    static void store(BYTE* const base, Offset off, const BundlelinkData& d, uint32_t v = FHIR_VERSION_R5) { STORE_FF_BUNDLE_LINK(base, off, d, v); }
    static BundlelinkData read(const BYTE* const base, Offset off, Size size, uint32_t v) { return FF_DESERIALIZE_BUNDLE_LINK(base, off, size, v); }
};
} // namespace FastFHIR

namespace FastFHIR {
template<> struct TypeTraits<BundleentryrequestData> {
    static constexpr auto recovery = RECOVER_FF_BUNDLE_ENTRY_REQUEST;
    static Size size(const BundleentryrequestData& d, uint32_t v = FHIR_VERSION_R5) { return SIZE_FF_BUNDLE_ENTRY_REQUEST(d, v); }
    static void store(BYTE* const base, Offset off, const BundleentryrequestData& d, uint32_t v = FHIR_VERSION_R5) { STORE_FF_BUNDLE_ENTRY_REQUEST(base, off, d, v); }
    static BundleentryrequestData read(const BYTE* const base, Offset off, Size size, uint32_t v) { return FF_DESERIALIZE_BUNDLE_ENTRY_REQUEST(base, off, size, v); }
};
} // namespace FastFHIR

namespace FastFHIR {
template<> struct TypeTraits<BundleentrysearchData> {
    static constexpr auto recovery = RECOVER_FF_BUNDLE_ENTRY_SEARCH;
    static Size size(const BundleentrysearchData& d, uint32_t v = FHIR_VERSION_R5) { return SIZE_FF_BUNDLE_ENTRY_SEARCH(d, v); }
    static void store(BYTE* const base, Offset off, const BundleentrysearchData& d, uint32_t v = FHIR_VERSION_R5) { STORE_FF_BUNDLE_ENTRY_SEARCH(base, off, d, v); }
    static BundleentrysearchData read(const BYTE* const base, Offset off, Size size, uint32_t v) { return FF_DESERIALIZE_BUNDLE_ENTRY_SEARCH(base, off, size, v); }
};
} // namespace FastFHIR

namespace FastFHIR {
template<> struct TypeTraits<BundleentryresponseData> {
    static constexpr auto recovery = RECOVER_FF_BUNDLE_ENTRY_RESPONSE;
    static Size size(const BundleentryresponseData& d, uint32_t v = FHIR_VERSION_R5) { return SIZE_FF_BUNDLE_ENTRY_RESPONSE(d, v); }
    static void store(BYTE* const base, Offset off, const BundleentryresponseData& d, uint32_t v = FHIR_VERSION_R5) { STORE_FF_BUNDLE_ENTRY_RESPONSE(base, off, d, v); }
    static BundleentryresponseData read(const BYTE* const base, Offset off, Size size, uint32_t v) { return FF_DESERIALIZE_BUNDLE_ENTRY_RESPONSE(base, off, size, v); }
};
} // namespace FastFHIR

namespace FastFHIR {
template<> struct TypeTraits<BundleentryData> {
    static constexpr auto recovery = RECOVER_FF_BUNDLE_ENTRY;
    static Size size(const BundleentryData& d, uint32_t v = FHIR_VERSION_R5) { return SIZE_FF_BUNDLE_ENTRY(d, v); }
    static void store(BYTE* const base, Offset off, const BundleentryData& d, uint32_t v = FHIR_VERSION_R5) { STORE_FF_BUNDLE_ENTRY(base, off, d, v); }
    static BundleentryData read(const BYTE* const base, Offset off, Size size, uint32_t v) { return FF_DESERIALIZE_BUNDLE_ENTRY(base, off, size, v); }
};
} // namespace FastFHIR

namespace FastFHIR {
template<> struct TypeTraits<BundleData> {
    static constexpr auto recovery = RECOVER_FF_BUNDLE;
    static Size size(const BundleData& d, uint32_t v = FHIR_VERSION_R5) { return SIZE_FF_BUNDLE(d, v); }
    static void store(BYTE* const base, Offset off, const BundleData& d, uint32_t v = FHIR_VERSION_R5) { STORE_FF_BUNDLE(base, off, d, v); }
    static BundleData read(const BYTE* const base, Offset off, Size size, uint32_t v) { return FF_DESERIALIZE_BUNDLE(base, off, size, v); }
};
} // namespace FastFHIR

